/** SQL tạo bảng lịch dạy GV — chạy một lần trên Supabase SQL Editor. */
export const SQL_SETUP_LICH_DAY_GV = `-- Bảng lịch dạy giáo viên (admin)
create table if not exists public.hr_lich_day_giao_vien (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  chi_nhanh_id bigint not null references public.ql_chi_nhanh (id) on delete cascade,
  tuan_bat_dau date not null,
  thu smallint not null check (thu between 1 and 7),
  ca text not null check (ca in ('sang', 'chieu', 'toi')),
  nhom text not null default 'hinh' check (nhom in ('hinh', 'mau')),
  nhan_su_id bigint not null references public.hr_nhan_su (id) on delete cascade,
  ghi_chu text,
  nguoi_tao_id bigint references public.hr_nhan_su (id) on delete set null,
  unique (chi_nhanh_id, tuan_bat_dau, thu, ca, nhom, nhan_su_id)
);
create index if not exists hr_lich_day_giao_vien_lookup_idx
  on public.hr_lich_day_giao_vien (chi_nhanh_id, tuan_bat_dau);

grant all on table public.hr_lich_day_giao_vien to service_role;
do $$
declare seq_name text;
begin
  select pg_get_serial_sequence('public.hr_lich_day_giao_vien', 'id') into seq_name;
  if seq_name is not null then
    execute format('grant usage, select, update on sequence %s to service_role', seq_name);
  end if;
end $$;`;

/**
 * Migration: cho phép cùng một GV trong cả hàng Hình và Màu (cùng ca).
 * Chạy nếu thêm GV vào nhóm thứ hai báo lỗi trùng / unique constraint.
 */
export const SQL_MIGRATE_LICH_DAY_GV_NHOM = `-- Migration: cột nhom + unique theo (thu, ca, nhom, nhan_su_id)
alter table public.hr_lich_day_giao_vien
  add column if not exists nhom text not null default 'hinh';

update public.hr_lich_day_giao_vien set nhom = 'hinh' where nhom is null or nhom = '';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'hr_lich_day_giao_vien_nhom_check'
      and conrelid = 'public.hr_lich_day_giao_vien'::regclass
  ) then
    alter table public.hr_lich_day_giao_vien
      add constraint hr_lich_day_giao_vien_nhom_check check (nhom in ('hinh', 'mau'));
  end if;
end $$;

-- Gỡ unique cũ (không có cột nhom) — tên tự sinh khi tạo bảng ban đầu
alter table public.hr_lich_day_giao_vien
  drop constraint if exists hr_lich_day_giao_vien_chi_nhanh_id_tuan_bat_dau_thu_ca_nhan_su_id_key;

do $$
declare r record;
begin
  for r in
    select c.conname
    from pg_constraint c
    join pg_class t on c.conrelid = t.oid
    join pg_namespace n on t.relnamespace = n.oid
    where n.nspname = 'public'
      and t.relname = 'hr_lich_day_giao_vien'
      and c.contype = 'u'
      and not exists (
        select 1
        from pg_attribute a
        where a.attrelid = t.oid
          and a.attnum = any (c.conkey)
          and a.attname = 'nhom'
          and not a.attisdropped
      )
  loop
    execute format(
      'alter table public.hr_lich_day_giao_vien drop constraint if exists %I',
      r.conname
    );
  end loop;
end $$;

create unique index if not exists hr_lich_day_giao_vien_slot_nhom_uidx
  on public.hr_lich_day_giao_vien (chi_nhanh_id, tuan_bat_dau, thu, ca, nhom, nhan_su_id);

grant all on table public.hr_lich_day_giao_vien to service_role;`;
