-- Phiếu chuyển kho họa cụ giữa chi nhánh.
-- Chạy trong Supabase SQL Editor (cùng lúc hoặc sau hc-danh-sach-chi-nhanh-id.sql).

CREATE TABLE IF NOT EXISTS hc_chuyen_kho (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  nguoi_chuyen bigint REFERENCES hr_nhan_su(id),
  chi_nhanh_nguon bigint NOT NULL REFERENCES ql_chi_nhanh(id),
  chi_nhanh_dich bigint NOT NULL REFERENCES ql_chi_nhanh(id),
  ghi_chu text,
  idempotency_key text UNIQUE
);

CREATE INDEX IF NOT EXISTS idx_hc_chuyen_kho_created_at ON hc_chuyen_kho(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_hc_chuyen_kho_nguon ON hc_chuyen_kho(chi_nhanh_nguon);
CREATE INDEX IF NOT EXISTS idx_hc_chuyen_kho_dich ON hc_chuyen_kho(chi_nhanh_dich);

CREATE TABLE IF NOT EXISTS hc_chuyen_kho_chi_tiet (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  don_chuyen bigint NOT NULL REFERENCES hc_chuyen_kho(id) ON DELETE CASCADE,
  mat_hang_nguon bigint NOT NULL REFERENCES hc_danh_sach_san_pham(id),
  mat_hang_dich bigint NOT NULL REFERENCES hc_danh_sach_san_pham(id),
  so_luong integer NOT NULL DEFAULT 1 CHECK (so_luong > 0),
  gia_nhap_snapshot numeric NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_hc_chuyen_kho_chi_tiet_don ON hc_chuyen_kho_chi_tiet(don_chuyen);
CREATE INDEX IF NOT EXISTS idx_hc_chuyen_kho_chi_tiet_nguon ON hc_chuyen_kho_chi_tiet(mat_hang_nguon);
CREATE INDEX IF NOT EXISTS idx_hc_chuyen_kho_chi_tiet_dich ON hc_chuyen_kho_chi_tiet(mat_hang_dich);
