-- =====================================================================
-- 2026-05-09 — dh_mon_thi: danh mục môn / hình thức thi
-- =====================================================================
-- Chạy trong Supabase SQL Editor (project izqoovekasfsapvbxmgm).
-- Idempotent — có thể chạy lại nhiều lần an toàn.
-- =====================================================================

-- 1) Bảng danh mục
CREATE TABLE IF NOT EXISTS public.dh_mon_thi (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten_mon     TEXT NOT NULL,
  thu_tu      INTEGER NOT NULL DEFAULT 99,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS dh_mon_thi_ten_mon_uniq
  ON public.dh_mon_thi (ten_mon);

CREATE INDEX IF NOT EXISTS dh_mon_thi_thu_tu_ten_idx
  ON public.dh_mon_thi (thu_tu, ten_mon);

-- 2) RLS — service_role bypass; anon chỉ SELECT
ALTER TABLE public.dh_mon_thi ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dh_mon_thi_select_anon ON public.dh_mon_thi;
CREATE POLICY dh_mon_thi_select_anon
  ON public.dh_mon_thi
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- 3) Seed dữ liệu cũ (idempotent)
INSERT INTO public.dh_mon_thi (ten_mon, thu_tu) VALUES
  (N'Xét duyệt',              10),
  (N'Hình họa khối cơ bản',   20),
  (N'Hình họa tĩnh vật',      30),
  (N'Hình họa tượng tròn',    40),
  (N'Hình họa chân dung',     50),
  (N'Hình họa toàn thân',     60),
  (N'Trang trí màu',          70),
  (N'Bố cục màu',             80)
ON CONFLICT (ten_mon) DO NOTHING;
