"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState, useTransition } from "react";
import {
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  Copy,
  Eye,
  EyeOff,
  Loader2,
  Pencil,
  Plus,
  X,
  Check,
} from "lucide-react";

import {
  assignLichDayGiaoVienMany,
  copyLichDayFromPreviousWeek,
  removeLichDayGiaoVien,
} from "@/app/admin/dashboard/lich-day-giao-vien/actions";
import type { AdminChiNhanhOption } from "@/lib/data/admin-chi-nhanh";
import type { LichDayGvAssignment, LichDayGvTeacherOption } from "@/lib/data/admin-lich-day-gv";
import {
  CA_LABELS,
  CA_ORDER,
  THU_ORDER,
  NHOM_LABELS,
  NHOM_ORDER,
  addWeeksToMonday,
  formatThuHeader,
  formatWeekRange,
  mondayOfToday,
  slotKey,
  isCaDay,
  type CaDay,
  type NhomDay,
  type ThuInWeek,
} from "@/lib/lich-day-gv/config";
import { teacherMatchesNhomPick } from "@/lib/lich-day-gv/mon-nhom";
import { cn } from "@/lib/utils";

type Props = {
  branches: AdminChiNhanhOption[];
  branchError: string | null;
  chiNhanhId: number;
  tuanBatDau: string;
  assignments: LichDayGvAssignment[];
  scheduleError: string | null;
  missingTable: boolean;
  permissionDenied: boolean;
  teachers: LichDayGvTeacherOption[];
  teachersError: string | null;
};

type PickSlot = { thu: ThuInWeek; ca: CaDay; nhom: NhomDay } | null;

const HIDDEN_CA_STORAGE_KEY = "sineart.lich-day-gv.hiddenCa";

function readHiddenCaFromStorage(): Set<CaDay> {
  if (typeof window === "undefined") return new Set(["sang"]);
  try {
    const raw = localStorage.getItem(HIDDEN_CA_STORAGE_KEY);
    if (raw === null) return new Set(["sang"]);
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) return new Set(["sang"]);
    return new Set(parsed.filter((x): x is CaDay => typeof x === "string" && isCaDay(x)));
  } catch {
    return new Set(["sang"]);
  }
}

function writeHiddenCaToStorage(hidden: Set<CaDay>): void {
  try {
    localStorage.setItem(HIDDEN_CA_STORAGE_KEY, JSON.stringify([...hidden]));
  } catch {
    /* ignore */
  }
}

const SQL_SETUP = `-- Bảng lịch dạy giáo viên (admin)
create table if not exists public.hr_lich_day_giao_vien (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  chi_nhanh_id bigint not null references public.ql_chi_nhanh (id) on delete cascade,
  tuan_bat_dau date not null,
  thu smallint not null check (thu between 1 and 7),
  ca text not null check (ca in ('sang', 'chieu', 'toi')),
  nhom text not null default 'hinh' check (nhom in ('hinh', 'mau')),
  nhan_su_id bigint not null references public.hr_nhan_su (id) on delete cascade,
  ghi_chu text,
  nguoi_tao_id bigint references public.hr_nhan_su (id) on delete set null,
  unique (chi_nhanh_id, tuan_bat_dau, thu, ca, nhom, nhan_su_id)
);
create index if not exists hr_lich_day_giao_vien_lookup_idx
  on public.hr_lich_day_giao_vien (chi_nhanh_id, tuan_bat_dau);

-- Nếu bảng đã tạo trước đó (chưa có nhom), chạy thêm:
-- alter table public.hr_lich_day_giao_vien add column if not exists nhom text not null default 'hinh' check (nhom in ('hinh', 'mau'));
-- alter table public.hr_lich_day_giao_vien drop constraint if exists hr_lich_day_giao_vien_chi_nhanh_id_tuan_bat_dau_thu_ca_nhan_su_id_key;
-- create unique index if not exists hr_lich_day_giao_vien_slot_nhom_uidx on public.hr_lich_day_giao_vien (chi_nhanh_id, tuan_bat_dau, thu, ca, nhom, nhan_su_id);

-- Bắt buộc: quyền cho service_role (admin API)
grant all on table public.hr_lich_day_giao_vien to service_role;
do $$
declare seq_name text;
begin
  select pg_get_serial_sequence('public.hr_lich_day_giao_vien', 'id') into seq_name;
  if seq_name is not null then
    execute format('grant usage, select, update on sequence %s to service_role', seq_name);
  end if;
end $$;`;

function buildHref(chiNhanhId: number, tuan: string): string {
  const q = new URLSearchParams();
  q.set("chi_nhanh", String(chiNhanhId));
  q.set("tuan", tuan);
  return `/admin/dashboard/lich-day-giao-vien?${q.toString()}`;
}

function nhomSlotStyles(nhom: NhomDay): {
  box: string;
  label: string;
  addBtn: string;
} {
  if (nhom === "hinh") {
    return {
      box: "rounded-lg border border-[#F0D5A8] bg-[#FFF9F0] p-1",
      label: "text-[#B45309]",
      addBtn: "border-dashed border-[#E8C078]/70 bg-white/80 text-[#B45309] hover:bg-white",
    };
  }
  return {
    box: "rounded-lg border border-[#D4C4F8] bg-[#F7F3FF] p-1",
    label: "text-[#7C3AED]",
    addBtn: "border-dashed border-[#BC8AF9]/50 bg-white/80 text-[#7C3AED] hover:bg-white",
  };
}

function TeacherPickerAvatar({
  name,
  src,
  size = 40,
}: {
  name: string;
  src?: string | null;
  size?: number;
}) {
  const [err, setErr] = useState(false);
  const initial = name.trim().charAt(0).toUpperCase() || "?";
  if (src && !err) {
    return (
      // eslint-disable-next-line @next/next/no-img-element
      <img
        src={src}
        alt=""
        width={size}
        height={size}
        className="shrink-0 rounded-full object-cover ring-1 ring-black/[0.06]"
        style={{ width: size, height: size }}
        onError={() => setErr(true)}
      />
    );
  }
  return (
    <div
      className="flex shrink-0 items-center justify-center rounded-full text-[13px] font-bold text-white ring-1 ring-black/[0.06]"
      style={{
        width: size,
        height: size,
        background: "linear-gradient(135deg,#BC8AF9,#ED5C9D)",
      }}
    >
      {initial}
    </div>
  );
}

export default function LichDayGvView({
  branches,
  branchError,
  chiNhanhId,
  tuanBatDau,
  assignments,
  scheduleError,
  missingTable,
  permissionDenied,
  teachers,
  teachersError,
}: Props) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [pickSlot, setPickSlot] = useState<PickSlot>(null);
  const [teacherQ, setTeacherQ] = useState("");
  const [pickerSelected, setPickerSelected] = useState<number[]>([]);
  const [hiddenCa, setHiddenCa] = useState<Set<CaDay>>(() => new Set(["sang"]));
  const [isEditMode, setIsEditMode] = useState(false);

  useEffect(() => {
    setHiddenCa(readHiddenCaFromStorage());
  }, []);

  const visibleCaOrder = useMemo(
    () => CA_ORDER.filter((ca) => !hiddenCa.has(ca)),
    [hiddenCa],
  );

  function toggleCaVisibility(ca: CaDay): void {
    setHiddenCa((prev) => {
      const next = new Set(prev);
      if (next.has(ca)) next.delete(ca);
      else next.add(ca);
      writeHiddenCaToStorage(next);
      return next;
    });
  }
  const [actionError, setActionError] = useState<string | null>(null);
  const [actionOk, setActionOk] = useState<string | null>(null);

  const bySlot = useMemo(() => {
    const m = new Map<string, LichDayGvAssignment[]>();
    for (const a of assignments) {
      const k = slotKey(a.thu, a.ca, a.nhom);
      if (!m.has(k)) m.set(k, []);
      m.get(k)!.push(a);
    }
    return m;
  }, [assignments]);

  const filteredTeachers = useMemo(() => {
    const q = teacherQ.trim().toLowerCase();
    let list = [...teachers].sort((a, b) => {
      const aMatch = a.chi_nhanh_id === chiNhanhId ? 0 : 1;
      const bMatch = b.chi_nhanh_id === chiNhanhId ? 0 : 1;
      if (aMatch !== bMatch) return aMatch - bMatch;
      return a.full_name.localeCompare(b.full_name, "vi");
    });
    if (pickSlot) {
      list = list.filter((t) => teacherMatchesNhomPick(t.nhom_flags, pickSlot.nhom));
    }
    if (!q) return list;
    return list.filter(
      (t) =>
        t.full_name.toLowerCase().includes(q) ||
        t.lop_dang_day_labels.some((lop) => lop.toLowerCase().includes(q)),
    );
  }, [teachers, teacherQ, chiNhanhId, pickSlot]);

  const assignedIdsInPick = useMemo(() => {
    if (!pickSlot) return new Set<number>();
    const rows = bySlot.get(slotKey(pickSlot.thu, pickSlot.ca, pickSlot.nhom)) ?? [];
    return new Set(rows.map((r) => r.nhan_su_id));
  }, [pickSlot, bySlot]);

  const isCurrentWeek = tuanBatDau === mondayOfToday();

  function closePicker(): void {
    setPickSlot(null);
    setTeacherQ("");
    setPickerSelected([]);
  }

  function togglePickerTeacher(id: number): void {
    if (assignedIdsInPick.has(id)) return;
    setPickerSelected((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id],
    );
  }

  function exitEditMode(): void {
    closePicker();
    setIsEditMode(false);
  }

  function runAction(
    fn: () => Promise<{ ok: boolean; error?: string; copied?: number; added?: number }>,
    opts?: { closePicker?: boolean },
  ) {
    setActionError(null);
    setActionOk(null);
    startTransition(async () => {
      const res = await fn();
      if (!res.ok) {
        setActionError(res.error ?? "Lỗi không xác định.");
        return;
      }
      if ("copied" in res && res.copied != null) {
        setActionOk(`Đã sao chép ${res.copied} ca từ tuần trước.`);
      } else if ("added" in res && res.added != null) {
        setActionOk(`Đã thêm ${res.added} giáo viên.`);
      } else {
        setActionOk("Đã lưu.");
      }
      if (opts?.closePicker) {
        closePicker();
      }
      router.refresh();
    });
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h1 className="m-0 flex items-center gap-2 text-xl font-bold tracking-tight text-[#1a1a2e]">
            <CalendarDays className="h-5 w-5 text-[#BC8AF9]" aria-hidden />
            Lịch dạy giáo viên
          </h1>
          <p className="mt-1 mb-0 max-w-2xl text-[13px] leading-snug text-black/50">
            Mỗi chi nhánh có lịch riêng. Gán giáo viên theo tuần (Thứ 2 → Chủ nhật). Có thể ẩn ca không dùng (vd. Sáng).
          </p>
        </div>
      </div>

      {branchError ? (
        <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-[13px] text-amber-950">
          Không tải được chi nhánh: {branchError}
        </div>
      ) : null}

      {missingTable || permissionDenied ? (
        <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-[13px] leading-relaxed text-amber-950">
          <p className="m-0 font-semibold">
            {permissionDenied && !missingTable
              ? "Thiếu quyền truy cập bảng lịch (permission denied)"
              : "Chưa có bảng lịch trên Supabase"}
          </p>
          <p className="mt-1 mb-2 text-[12px]">
            {permissionDenied && !missingTable
              ? "Bảng đã tạo nhưng chưa GRANT cho service_role. Chạy toàn bộ SQL sau (an toàn nếu bảng đã có), rồi tải lại trang:"
              : "Chạy SQL sau trong Supabase → SQL Editor (một lần), rồi tải lại trang:"}
          </p>
          <pre className="max-h-48 overflow-auto rounded-xl bg-white/80 p-3 text-[11px] text-black/80">{SQL_SETUP}</pre>
        </div>
      ) : scheduleError ? (
        <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-[13px] text-red-800">
          {scheduleError}
        </div>
      ) : null}

      {teachersError ? (
        <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-[13px] text-amber-950">
          Không tải danh sách giáo viên: {teachersError}
        </div>
      ) : null}

      {actionError ? (
        <div className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-[13px] text-red-800">
          {actionError}
        </div>
      ) : null}
      {actionOk ? (
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-[13px] text-emerald-900">
          {actionOk}
        </div>
      ) : null}

      {branches.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-[#EDE8E9] bg-white px-6 py-10 text-center text-[13px] text-black/50">
          Chưa có chi nhánh.{" "}
          <Link href="/admin/dashboard/chi-nhanh" className="font-semibold text-[#7c3aed] underline">
            Thêm chi nhánh
          </Link>{" "}
          trước.
        </div>
      ) : (
        <>
          <div className="flex flex-wrap items-center gap-2">
            {branches.map((b) => (
              <Link
                key={b.id}
                href={buildHref(b.id, tuanBatDau)}
                className={cn(
                  "rounded-full px-3 py-1.5 text-[12px] font-semibold transition",
                  b.id === chiNhanhId
                    ? "bg-gradient-to-r from-[#f8a668] to-[#ee5b9f] text-white shadow-sm"
                    : "border border-black/[0.08] bg-white text-black/65 hover:bg-black/[0.03]",
                )}
              >
                {b.ten}
              </Link>
            ))}
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-black/[0.06] bg-[#fafafa]/80 px-3 py-2">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-[11px] font-semibold text-black/45">Hiển thị ca:</span>
              {CA_ORDER.map((ca) => {
                const visible = !hiddenCa.has(ca);
                return (
                  <button
                    key={ca}
                    type="button"
                    onClick={() => toggleCaVisibility(ca)}
                    className={cn(
                      "inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold transition",
                      visible
                        ? "bg-white text-[#7c3aed] shadow-sm ring-1 ring-[#BC8AF9]/25"
                        : "text-black/35 hover:bg-white/80",
                    )}
                    aria-pressed={visible}
                    title={visible ? `Ẩn ca ${CA_LABELS[ca]}` : `Hiện ca ${CA_LABELS[ca]}`}
                  >
                    {visible ? (
                      <Eye className="h-3 w-3 shrink-0" aria-hidden />
                    ) : (
                      <EyeOff className="h-3 w-3 shrink-0" aria-hidden />
                    )}
                    {CA_LABELS[ca]}
                  </button>
                );
              })}
            </div>
            <div className="flex flex-wrap items-center gap-2">
              {!isEditMode ? (
                <span className="text-[11px] font-medium text-black/40">Chế độ xem</span>
              ) : (
                <button
                  type="button"
                  disabled={pending || chiNhanhId <= 0 || missingTable || permissionDenied}
                  onClick={() =>
                    runAction(() =>
                      copyLichDayFromPreviousWeek({ chi_nhanh_id: chiNhanhId, tuan_bat_dau: tuanBatDau }),
                    )
                  }
                  className="inline-flex items-center gap-1 rounded-full border border-black/[0.08] bg-white px-2.5 py-1 text-[11px] font-semibold text-black/70 shadow-sm transition hover:bg-black/[0.03] disabled:opacity-50"
                >
                  <Copy className="h-3 w-3" aria-hidden />
                  Sao chép tuần trước
                </button>
              )}
              <button
                type="button"
                disabled={pending}
                onClick={() => {
                  if (isEditMode) exitEditMode();
                  else setIsEditMode(true);
                }}
                className={cn(
                  "inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-semibold transition disabled:opacity-50",
                  isEditMode
                    ? "bg-[#1a1a2e] text-white shadow-sm hover:opacity-90"
                    : "bg-[#BC8AF9] text-white shadow-sm hover:opacity-90",
                )}
              >
                {isEditMode ? (
                  <>
                    <Check className="h-3 w-3" aria-hidden />
                    Xong
                  </>
                ) : (
                  <>
                    <Pencil className="h-3 w-3" aria-hidden />
                    Chỉnh sửa
                  </>
                )}
              </button>
            </div>
          </div>

          <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-black/[0.08] bg-white px-4 py-3 shadow-sm">
            <Link
              href={buildHref(chiNhanhId, addWeeksToMonday(tuanBatDau, -1))}
              className="inline-flex items-center gap-1 rounded-xl px-2 py-1.5 text-[13px] font-semibold text-black/70 hover:bg-black/[0.04]"
            >
              <ChevronLeft className="h-4 w-4" aria-hidden />
              Tuần trước
            </Link>
            <div className="text-center">
              <div className="text-[14px] font-bold text-[#1a1a2e]">{formatWeekRange(tuanBatDau)}</div>
              {isCurrentWeek ? (
                <div className="text-[11px] font-medium text-[#BC8AF9]">Tuần hiện tại</div>
              ) : (
                <Link
                  href={buildHref(chiNhanhId, mondayOfToday())}
                  className="text-[11px] font-semibold text-[#7c3aed] hover:underline"
                >
                  Về tuần này
                </Link>
              )}
            </div>
            <Link
              href={buildHref(chiNhanhId, addWeeksToMonday(tuanBatDau, 1))}
              className="inline-flex items-center gap-1 rounded-xl px-2 py-1.5 text-[13px] font-semibold text-black/70 hover:bg-black/[0.04]"
            >
              Tuần sau
              <ChevronRight className="h-4 w-4" aria-hidden />
            </Link>
          </div>

          <div className="overflow-x-auto rounded-2xl border border-black/[0.08] bg-white shadow-sm">
            <table className="w-full min-w-[880px] border-collapse text-[13px]">
              <thead>
                <tr className="border-b border-black/[0.06] bg-[#fafafa] text-left text-[10px] font-bold uppercase tracking-wide text-[#9E8A90]">
                  <th className="sticky left-0 z-[1] w-24 bg-[#fafafa] px-3 py-3">Ca</th>
                  {THU_ORDER.map((thu) => (
                    <th key={thu} className="px-2 py-3 text-center font-semibold normal-case text-black/55">
                      {formatThuHeader(tuanBatDau, thu)}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {visibleCaOrder.length === 0 ? (
                  <tr>
                    <td
                      colSpan={THU_ORDER.length + 1}
                      className="px-4 py-8 text-center text-[13px] text-black/45"
                    >
                      Đang ẩn tất cả ca — bật lại ít nhất một ca ở trên.
                    </td>
                  </tr>
                ) : (
                  visibleCaOrder.map((ca) => (
                  <tr key={ca} className="border-b border-black/[0.04] last:border-b-0">
                    <td className="sticky left-0 z-[1] bg-white px-3 py-3 align-top font-semibold text-[#323232]">
                      {CA_LABELS[ca]}
                    </td>
                    {THU_ORDER.map((thu) => (
                      <td key={thu} className="min-w-[110px] align-top px-1 py-1">
                        <div className="flex flex-col gap-0.5">
                          {NHOM_ORDER.map((nhom) => {
                            const rows = bySlot.get(slotKey(thu, ca, nhom)) ?? [];
                            const surface = nhomSlotStyles(nhom);
                            return (
                              <div key={nhom} className={cn("flex flex-col gap-0.5", surface.box)}>
                                <div
                                  className={cn(
                                    "px-0.5 text-[9px] font-bold uppercase leading-none tracking-wide",
                                    surface.label,
                                  )}
                                >
                                  {NHOM_LABELS[nhom]}
                                </div>
                                {rows.map((r) => (
                                  <div key={r.id} className="relative pr-0.5">
                                    <div className="rounded-md bg-white px-1.5 py-1 text-[11px] shadow-sm ring-1 ring-black/[0.05]">
                                      <span className="block min-w-0 font-medium leading-tight text-[#1a1a2e]">
                                        {r.nhan_su_ten}
                                      </span>
                                      {r.nhan_su_sdt ? (
                                        <a
                                          href={`tel:${r.nhan_su_sdt.replace(/\s/g, "")}`}
                                          className="mt-px block text-[9px] leading-tight text-black/45 hover:text-[#7c3aed] hover:underline"
                                          onClick={(e) => e.stopPropagation()}
                                        >
                                          {r.nhan_su_sdt}
                                        </a>
                                      ) : null}
                                    </div>
                                    {isEditMode ? (
                                    <button
                                      type="button"
                                      disabled={pending}
                                      onClick={() =>
                                        runAction(() => removeLichDayGiaoVien(r.id).then((x) => x))
                                      }
                                      className="absolute -right-0.5 -top-0.5 z-[1] flex h-3.5 w-3.5 items-center justify-center rounded-full border border-black/[0.08] bg-white text-black/40 shadow-sm transition hover:border-red-200 hover:bg-red-50 hover:text-red-600 disabled:opacity-40"
                                      aria-label={`Gỡ ${r.nhan_su_ten}`}
                                    >
                                      <X className="h-2 w-2" strokeWidth={2.5} />
                                    </button>
                                    ) : null}
                                  </div>
                                ))}
                                {isEditMode ? (
                                <button
                                  type="button"
                                  disabled={pending || missingTable || permissionDenied}
                                  onClick={() => {
                                    setActionError(null);
                                    setPickSlot({ thu, ca, nhom });
                                    setTeacherQ("");
                                    setPickerSelected([]);
                                  }}
                                  className={cn(
                                    "inline-flex items-center justify-center gap-0.5 rounded-md py-0.5 text-[9px] font-semibold transition disabled:opacity-40",
                                    surface.addBtn,
                                  )}
                                >
                                  <Plus className="h-2.5 w-2.5" aria-hidden />
                                  Thêm
                                </button>
                                ) : null}
                              </div>
                            );
                          })}
                        </div>
                      </td>
                    ))}
                  </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </>
      )}

      {pickSlot && isEditMode ? (
        <div
          className="fixed inset-0 z-[200] flex items-end justify-center bg-black/40 p-4 sm:items-center"
          role="dialog"
          aria-modal="true"
          aria-labelledby="lich-pick-title"
          onClick={() => !pending && closePicker()}
        >
          <div
            className="flex max-h-[min(85vh,560px)] w-full max-w-lg flex-col overflow-hidden rounded-2xl bg-white shadow-[var(--shadow-md,0_10px_32px_rgba(45,32,32,.12))]"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between border-b border-black/[0.06] px-4 py-3">
              <div>
                <h2 id="lich-pick-title" className="m-0 text-[15px] font-bold text-[#1a1a2e]">
                  Thêm giáo viên
                </h2>
                <p className="m-0 mt-0.5 text-[12px] text-black/50">
                  {formatThuHeader(tuanBatDau, pickSlot.thu)} · {CA_LABELS[pickSlot.ca]} ·{" "}
                  {NHOM_LABELS[pickSlot.nhom]} · chọn nhiều GV
                </p>
              </div>
              <button
                type="button"
                onClick={closePicker}
                className="rounded-lg p-1.5 text-black/45 hover:bg-black/[0.05]"
                aria-label="Đóng"
              >
                <X className="h-5 w-5" />
              </button>
            </div>
            <div className="border-b border-black/[0.06] px-4 py-2">
              <input
                type="search"
                value={teacherQ}
                onChange={(e) => setTeacherQ(e.target.value)}
                placeholder="Tìm tên hoặc lớp đang dạy…"
                className="w-full rounded-xl border border-black/[0.08] bg-[#fafafa] px-3 py-2 text-[13px] outline-none ring-[#BC8AF9]/30 focus:ring-2"
                autoFocus
              />
            </div>
            <ul className="flex-1 overflow-y-auto p-2">
              {filteredTeachers.length === 0 ? (
                <li className="px-3 py-6 text-center text-[13px] text-black/45">
                  Không tìm thấy giáo viên ban Đào tạo.
                </li>
              ) : (
                filteredTeachers.map((t) => {
                  const taken = assignedIdsInPick.has(t.id);
                  const checked = taken || pickerSelected.includes(t.id);
                  return (
                    <li key={t.id}>
                      <label
                        className={cn(
                          "flex cursor-pointer items-center gap-3 rounded-xl px-3 py-2.5 transition",
                          taken
                            ? "cursor-not-allowed opacity-60"
                            : checked
                              ? "bg-[#BC8AF9]/08"
                              : "hover:bg-[#faf5ff]",
                        )}
                      >
                        <input
                          type="checkbox"
                          className="h-4 w-4 shrink-0 cursor-pointer rounded accent-[#BC8AF9] disabled:cursor-not-allowed"
                          checked={checked}
                          disabled={pending || taken}
                          onChange={() => togglePickerTeacher(t.id)}
                        />
                        <TeacherPickerAvatar name={t.full_name} src={t.avatar} size={40} />
                        <span className="min-w-0 flex-1">
                          <span
                            className={cn(
                              "block truncate text-[13px]",
                              taken ? "text-black/45" : checked ? "font-semibold text-[#1a1a2e]" : "text-[#1a1a2e]",
                            )}
                          >
                            {t.full_name}
                          </span>
                          {t.lop_dang_day_labels.length > 0 ? (
                            <span className="mt-0.5 flex flex-wrap gap-1">
                              {t.lop_dang_day_labels.map((lop) => (
                                <span
                                  key={lop}
                                  className="inline-flex max-w-full truncate rounded-md bg-[#E8F9F0] px-1.5 py-0.5 text-[10px] font-semibold text-[#1A9A5C]"
                                >
                                  {lop}
                                </span>
                              ))}
                            </span>
                          ) : (
                            <span className="mt-0.5 block text-[11px] text-black/40">Chưa có lớp đang dạy</span>
                          )}
                        </span>
                        <span className="flex shrink-0 flex-col items-end gap-1">
                          {t.chi_nhanh_id === chiNhanhId ? (
                            <span className="text-[10px] font-semibold text-[#BC8AF9]">CN này</span>
                          ) : null}
                          {taken ? (
                            <span className="text-[10px] text-black/40">Đã có</span>
                          ) : null}
                        </span>
                      </label>
                    </li>
                  );
                })
              )}
            </ul>
            <div className="flex items-center justify-between gap-3 border-t border-black/[0.06] bg-[#fafafa] px-4 py-3">
              <span className="text-[12px] text-black/50">
                {pickerSelected.length > 0
                  ? `Đã chọn ${pickerSelected.length} giáo viên`
                  : "Chưa chọn ai"}
              </span>
              <div className="flex items-center gap-2">
                {pickerSelected.length > 0 ? (
                  <button
                    type="button"
                    disabled={pending}
                    onClick={() => setPickerSelected([])}
                    className="rounded-full px-3 py-1.5 text-[12px] font-semibold text-red-500 transition hover:bg-red-50 disabled:opacity-50"
                  >
                    Bỏ chọn
                  </button>
                ) : null}
                <button
                  type="button"
                  disabled={pending || pickerSelected.length === 0}
                  onClick={() =>
                    runAction(
                      () =>
                        assignLichDayGiaoVienMany({
                          chi_nhanh_id: chiNhanhId,
                          tuan_bat_dau: tuanBatDau,
                          thu: pickSlot.thu,
                          ca: pickSlot.ca,
                          nhom: pickSlot.nhom,
                          nhan_su_ids: pickerSelected,
                        }),
                      { closePicker: true },
                    )
                  }
                  className="inline-flex items-center gap-1.5 rounded-full bg-[#BC8AF9] px-4 py-2 text-[12px] font-semibold text-white shadow-sm transition hover:opacity-90 disabled:opacity-50"
                >
                  {pending ? <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden /> : null}
                  Thêm vào ca
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {pending ? (
        <div className="pointer-events-none fixed bottom-6 right-6 z-[210] inline-flex items-center gap-2 rounded-full bg-[#1a1a2e] px-4 py-2 text-[12px] font-semibold text-white shadow-lg">
          <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
          Đang lưu…
        </div>
      ) : null}
    </div>
  );
}
