/**
 * Migration script: fetch content từ Supabase, tạo file _content.ts cho mỗi bài.
 * Chạy 1 lần: node scripts/migrate-content.mjs
 */
import https from "https";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const HOST = "izqoovekasfsapvbxmgm.supabase.co";
const KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cW9vdmVrYXNmc2FwdmJ4bWdtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDQxMTkzOCwiZXhwIjoyMDg5OTg3OTM4fQ.A_ZPSnrsxriS689kmj4JAjFyhbKEoAFonakIFPJYcU8";

function get(path) {
  return new Promise((resolve, reject) => {
    const opts = {
      hostname: HOST,
      path,
      method: "GET",
      headers: { apikey: KEY, Authorization: "Bearer " + KEY },
    };
    const req = https.request(opts, (res) => {
      let d = "";
      res.on("data", (c) => (d += c));
      res.on("end", () => resolve(JSON.parse(d)));
    });
    req.on("error", reject);
    req.end();
  });
}

const SLUGS = [
  "co-so-tao-hinh",
  "nguyen-ly-thi-giac",
  "phuong-phap-ve-gioi-han",
  "phuong-phap-ve-cau-truc",
  "ly-thuyet-phoi-canh",
  "diem-tap-trung",
  "bo-cuc-sac-do",
  "ti-le-co-the-nguoi",
  "khong-gian-mau",
  "ly-thuyet-hoa-sac",
  "he-thong-mau-munsell",
  "mo-hinh-cong-tru-mau",
  "thuoc-tinh-mau-sac",
  "mau-sac-qua-thiet-bi-dien-tu",
  "cac-he-mau-vat-ly",
  "phoi-canh-khi-quyen",
  "shading-la-gi",
  "ly-thuyet-vat-lieu",
  "bo-cuc-trong-tranh",
  "bo-cuc-trong-thiet-ke",
];

async function main() {
  console.log("Fetching all articles from Supabase...");
  const rows = await get(
    "/rest/v1/dt_ly_thuyet_nen_tang?select=slug,content,video,video_tham_khao_khac&order=id.asc"
  );

  const bySlug = Object.fromEntries(rows.map((r) => [r.slug, r]));

  let created = 0;
  for (const slug of SLUGS) {
    const row = bySlug[slug];
    const dir = path.join(ROOT, "src", "app", "kien-thuc-nen-tang", slug);
    fs.mkdirSync(dir, { recursive: true });

    const contentFile = path.join(dir, "_content.ts");
    // Skip if already has real content (not stub)
    if (fs.existsSync(contentFile)) {
      const existing = fs.readFileSync(contentFile, "utf8");
      if (!existing.includes("STUB")) {
        console.log(`  skip (already migrated): ${slug}`);
        continue;
      }
    }

    const content = row?.content ?? "";
    const video = row?.video ?? "";
    const videoRef = row?.video_tham_khao_khac ?? "";

    const ts = `// AUTO-GENERATED by scripts/migrate-content.mjs — edit trực tiếp để thay thế DB.
// Khi chuyển sang block components, xoá file này và import blocks trong page.tsx thay thế.

export const CONTENT_HTML = ${JSON.stringify(content)};

export const VIDEO_URL = ${JSON.stringify(video)};

export const VIDEO_REF_URL = ${JSON.stringify(videoRef)};
`;
    fs.writeFileSync(contentFile, ts, "utf8");
    console.log(`  ✓ ${slug} (${content.length} chars)`);
    created++;
  }

  console.log(`\nDone. Created/updated ${created} content files.`);
}

main().catch((e) => { console.error(e); process.exit(1); });
