-- ============================================================
-- Google Maps reviews → ql_danh_gia
-- Generated: 2026-04-21T04:46:30.091Z
-- Total: 65 reviews (5-sao, có nội dung ≥ 30 ký tự)
--
-- GHI CHÚ QUAN TRỌNG:
-- 1. Các dòng có -- [TRUNCATED] là review bị cắt ở Google Maps (kết thúc bằng "…").
--    Bạn cần mở từng review trên Google Maps, bấm "Xem thêm" rồi sửa noi_dung cho đủ.
-- 2. avatar_url để trống. Xem README bên dưới để upload ảnh lên Cloudflare Images và paste URL.
-- 3. khoa_hoc (FK → ql_mon_hoc.id) để NULL. Gán thủ công trong Supabase Studio sau khi
--    đọc nội dung review để đoán môn học (vd "hình họa" → id môn Hình hoạ).
-- ============================================================

INSERT INTO ql_danh_gia
  (ten_nguoi, avatar_url, noi_dung, so_sao, nguon, hien_thi)
VALUES
  ('Chi Nguyễn', NULL, 'Học phí lớp hạt dẻ nhưng mà giáo viên thì siêu chất lượng và nhiệt huyết luôn. Nhất là anh Kiên của lớp hh2, ảnh dạy siêu có tâm vs sửa bài siêu kĩ luôn đáy mn, dù lúc đầu ảnh hơi khó tính nma học lâu r mới bt ảnh tình cảm vs giảng bài kĩ …', 5, 'Google Maps', true),  -- [TRUNCATED] 3 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2pFNFJGcE9XbG8wV2xSeWFUa3lUM0J5Y2xWSlZXYxAB
  ('Kitty 1997', NULL, '10 sao. Học phí rẻ, chất lượng tốt, take care học viên. Môi trường học sạch đẹp tiện nghi 😍 …', 5, 'Google Maps', true),  -- [TRUNCATED] 3 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2pSMWRWSklkamgwVVVjdGFsVXhTbEZaYWxoSmIyYxAB
  ('Yến Như', NULL, 'Lớp 10 điểm nha, học phí ok với thành phố lớn như HCM mà giáo viên nhiệt huyết và giảng kĩ lắm, mình học online mà như offline ấy, siêu recommend❤', 5, 'Google Maps', true),  -- 2 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT25OaFpVRlhVVUZCVm1Ob2VtNXdaVzlhYmxFMldHYxAB
  ('Ly Nguyễn', NULL, 'Mình học onl ở trung tâm, thấy giảng viên nhiệt tình, sửa bài siêu kĩ ( có sửa bài ngoài giờ), cảm giác giảng viên rất take care mình. Mình học hình họa 4 lớp anh Tiến và trang trí màu 1 lớp chị Ngọc nha, siêu rcm mọi người học 2 lớp này, …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChZDSUhNMG9nS0VJQ0FnTUN3eHBic2NBEAE
  ('Minnal This is', NULL, 'Mình đã học tại trung tâm được gần 5 tháng, mấy anh chị giảng viên rất nhiệt tình và dễ thương.
Trung tâm đã cải thiện được những vấn đề trang trí màu mà mình đã mắc phải, và …', 5, 'Google Maps', true),  -- [TRUNCATED] 3 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2psTU9FcElRVTlDYzNKMVYxcGtlRzV5VW1OS1RYYxAB
  ('Linh Gia', NULL, 'Lớp oki lắm nha mn , nay tui biết điểm thi rồi mới lên đánh giá(⁠◍⁠•⁠ᴗ⁠•⁠◍⁠) , học phí hạt dẻ đc học nhiều buổi, độ take care của giảng viên so với hồi đầu lúc tui học thì đã đc cải thiện hơn. Cơ sở vật chất ổn áp hết á. Trung tâm hay mở …', 5, 'Google Maps', true),  -- [TRUNCATED] 8 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT20wNFRVZENaWFk1VG5OUVJHbHZkbmhVTTFOa2ExRRAB
  ('Hường Châu Thị Kim', NULL, 'Chị giảng viên dễ thương, giảng dễ hiểu,chuyên nghiệp, nhiệt tình, tương tác với học viên tốt. Em rất thích học online ở Sine Art.', 5, 'Google Maps', true),  -- 6 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT25GelprOVFTRVYzYnpWcE9XbzNSMDk1ZUdNdFMyYxAB
  ('Hân Nguyễn', NULL, 'Mình học lớp online và cảm nhận rõ sự tiến bộ từng ngày. Giảng viên cực kỳ tận tâm, sửa bài chi tiết, nhiệt tình và gần gũi, có support sửa bài ngoài giờ học.
Admin và anh/chị Sine siêu cute, nhiệt huyết, luôn hỗ trợ học viên.🫶 …', 5, 'Google Maps', true),  -- [TRUNCATED] 10 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2tOMldFRjFNWGhQZEdoaWRsSTNjelJsZVhKYWJWRRAB
  ('Xem thêm', NULL, 'Mình học lớp hình họa cấp tốc online thấy giảng viên có khả năng truyền đạt bá đạo tổng đài hay hết cứu, phương pháp dạy sigma linh hoạt, tối ưu dễ hiểu ác quỷ theo sát sau lưng từng bạn một. Giảng viên hài cốt hoang dã alpha wolf wolf, …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChdDSUhNMG9nS0VJQ0FnTURRMjQzaWtBRRAB
  ('Trâm Nguyễn Ngọc', NULL, 'Mình học onl thấy giảng viên rất nhiệt tình lun ạ, sửa bài khá kĩ kể cả ngoài giờ học. Rất rcm cho ai đang tìm lớp học vẽ onl nha', 5, 'Google Maps', true),  -- 7 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT21WWlFsb3RORmxPWld4TldXaHNaRE5LWldocWFrRRAB
  ('Tiến Trầnv', NULL, 'Giảng viên nhiệt tình, website của lớp cx rất xịn xò, cảm ơn a Tiến, a Kiên và a Khoa đã giúp đỡ em rất nhiều trong quá trình học tập 💖 …', 5, 'Google Maps', true),  -- [TRUNCATED] 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2taRE9YaFRkVE56UVdscWRUbEhWelZVTTJ4TllYYxAB
  ('Như Quỳnh', NULL, 'Em là học viên lớp onl cấp tốc ở tt. Lớp có lộ trình học rõ ràng, có cập nhật tiến độ của học viên, admin và anh chị giảng viên cuti lắm ạ, mấy a/c sửa bài nhiệt tình lắm, nói chung là ưngggg', 5, 'Google Maps', true),  -- 10 tháng trước · ChZDSUhNMG9nS0VQN3VvdGlOdXJxZGZnEAE
  ('Dương Hạ Linh', NULL, 'Mình học lớp onl, thấy giảng viên có tâm, tận tình. Quan trọng là ý thức học viên cx cần theo sát để tiến độ học tốt hơn', 5, 'Google Maps', true),  -- 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT25KV2RYQjZUeTFIVkV4S0xYWmZaM0Z3WDBwa1drRRAB
  ('Fy Gy', NULL, 'Giảng viên cực kì nhiệt tình và tận tâm luôn ạ, Sine art đã giúp mình có đc điểm số ngoài sức tưởng tượng chỉ trong 2 tháng cấp tốc. Cảm ơn Sine art rất nhiều ạ', 5, 'Google Maps', true),  -- 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT25ocU9FOHhhRU0zZERoMVFuUklNMlE0ZFVoMVluYxAB
  ('Đạt Thành', NULL, 'Em muốn cho trung tâm 15* mà ở đây đc 5* thâu. Giảng viên những ngày cận thi vừa đông vừa nhiệt tình. Thi xong r nhưng em vẫn muốn lên trung tâm mình chơi mãi thâu', 5, 'Google Maps', true),  -- 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2t4U2RYVXRPVTg1YVRFd1QwcDVXRlJvTm1kVVRsRRAB
  ('Thanh Vy', NULL, 'chương trình dạy kỹ lưỡng,đi sâu vào cốt lõi bài học , các anh chị giảng viên có tâm,vui vẻ thân thiện, gần gũi dới học viên, đôi lúc có bully nhg đều từ tình thương mà ra, không gian học mát mẻ sạch sẽ, đôi lúc có hơi đông do sắp thi, cần nên chủ động học tập, ko nên chờ đợi sửa bài vì ai cũng có việc he', 5, 'Google Maps', true),  -- 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2xJM1dDMHpjMll5T1VodlMxZFlVbk5OYlZwaE1uYxAB
  ('Anh Phương', NULL, 'Lớp học vẽ ở Sine Art mang đến trải nghiệm rất tích cực. Giáo trình rõ ràng, phù hợp cho cả người mới bắt đầu.
Điểm mình ấn tượng nhất là giảng viên – vừa có chuyên môn, vừa tận tâm. Nhất là lớp của anh Tiến, ảnh take care hs 24/24, vui vẻ và dễ gần vô cùng💖 …', 5, 'Google Maps', true),  -- [TRUNCATED] 11 tháng trước · ChZDSUhNMG9nS0VJQ0FnTUNZcWF5YWFnEAE
  ('Hân Ngọc', NULL, 'Em đánh giá thật là thầy dạy nói chuyện nhẹ nhàng với hài nha, kiểu nói chuyện rất thoải mái ấy =))) nhưng vẫn nghiêm túc sửa bài cho từng học sinh rất chi tiết và quan tâm đến tiến độ hiểu bài, làm bài của mọi người nha, chương trình học …', 5, 'Google Maps', true),  -- [TRUNCATED] 8 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2kxSmNYUkpXRXM1YVMxMmNEZGpVWGx1WkZaTk9IYxAB
  ('Tân Hoàng', NULL, 'Trải nghiệm học ở đây rất tốt. Giảng viên sửa bài rất nhiệt tình, còn sửa bài ngoài giờ nữa, thái độ rất vui vẻ, dễ thương. Bên trung tâm rất là quan tâm học sinh, tổ chức nhìu lần thi thử.', 5, 'Google Maps', true),  -- 10 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2xGVWMzWkZlak5JWDNoQmVXVlRhbkpPY1VveVJsRRAB
  ('ᴍᴇᴏᴡ ᴍᴇᴏᴡ', NULL, 'Mình học cả onl cả off ở Sine thấy anh chị giảng viên của cả hai lớp đều nhiệt tình, nói chiện teen gần gũi lắm luôn. Bài giảng lẫn lộ trình học đều rất rõ ràng, mình từ người hong biết gì về căn bản luôn mà học xong thấy bảnh hẳn =)))), cảm ơn Sine nhiều ạ 💖 …', 5, 'Google Maps', true),  -- [TRUNCATED] 11 tháng trước · ChdDSUhNMG9nS0VPejFqYm50NXBPSzNRRRAB
  ('Oanh kookie''ss', NULL, 'Siêu tuyệt vời luôn 😘❤️‍🔥
Mọi người trong trung tâm thân thiện, phòng ốc điều hoà mát rượi 10đ không có gì để chê …', 5, 'Google Maps', true),  -- [TRUNCATED] 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT25odFMwWjNZVE01TVhWTmVHWkpRV3hQZG1ORGRsRRAB
  ('Phạm Nguyễn Kim Hằng', NULL, 'giảng viên nhiệt tình, học bài bản quá tr lun, chăm chỉ cố gắng là mấy ảnh chị cưng như trứng:).Mình học hình hoạ 2 của a Kiên, mình k bt mấy a chj giảng viên khác ntn nhma thật sự anh có tâm, admin page thì dthw dô cùng luôn ạ;-;', 5, 'Google Maps', true),  -- 10 tháng trước · ChZDSUhNMG9nS0VOeWtycmFBaXZlUUZBEAE
  ('Phuong Phuong', NULL, 'Mk hc on ở sine cả môn TTM và HH.
Hệ thống bài giảng thì chi tiết đầy đủ, có video bài giảng để mình xem trước, bài tập và video thị phạm rõ ràng. Lên lớp đc gv hướng dẫn, sửa bài chi tiết. Dc …', 5, 'Google Maps', true),  -- [TRUNCATED] 10 tháng trước · ChZDSUhNMG9nS0VJdXQ2S1RENmNDOUNnEAE
  ('Kim Thùy', NULL, 'ad tư vấn nhiệt tình, a giáo sửa bài siêu kĩ, rất ok luôn ạa', 5, 'Google Maps', true),  -- 5 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2pJelYwd3lkMmhtTURoMk1EQkZRM3BzU1hkb2MyYxAB
  ('Nguyễn Hoàng Oanh', NULL, 'Theo mình khi học ở Sine thì thoải mái, giảng viên có tâm vs nch teen lắm :3
Học phần chi tiết, chỉnh chu hơn các lớp mà mình từng học', 5, 'Google Maps', true),  -- một năm trước · ChZDSUhNMG9nS0VJQ0FnTURBM09YM1N3EAE
  ('Toàn Nguyễn Thanh', NULL, 'Mik thật sự rất vui khi đc đồng hành cùng sine. Khi ở sine mik cảm giác thoải mái khi hc hơn là những chổ hc trc. Nếu có co hội mik sẽ hc trực tiếp ở trung tâm và gt thêm những tv khác trong gia đình', 5, 'Google Maps', true),  -- 10 tháng trước · ChdDSUhNMG9nS0VQcVd4SVdqMDRxVjN3RRAB
  ('Khang Gia', NULL, 'Mình học online chì của anh K, học rất oke, gvien tận tình luôn hết mình, hehe rất vui vì chọn đúng trung tâm để học🥰🫶 …', 5, 'Google Maps', true),  -- [TRUNCATED] 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT21wNk5EQlRhbVZzYXpORE5VNVlabWxaT1dRMU0xRRAB
  ('Thùy Đoan', NULL, 'Học ổn, giảng viên nhiệt tình với học viên', 5, 'Google Maps', true),  -- 4 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2pCQlVHbG9OelZHUzFGMGIzSnZXVzVUVEdzd00wRRAB
  ('nguyen bao', NULL, 'Giảng viên nhiệt tình, thân thiện, giáo trình rõ ràng. Em cảm ơn anh chị rất nhiều vì đã hỗ trợ em trong khoảng thời gian thi cử ạ', 5, 'Google Maps', true),  -- 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2tKMFgxbE5VRlJHVTNKS1R5MVNWVTB5U1dadlQzYxAB
  ('Minh Nguyệt', NULL, 'Mình học cả online và offline ở đây. Lộ trình dạy học cụ thể, hiệu quả, đặc biệt là giảng viên siêu nhiệt tình, tận tâm. Rất chất lượng và uy tín ạ!', 5, 'Google Maps', true),  -- 10 tháng trước · ChdDSUhNMG9nS0VOcVl0SXZnN1pIRjVRRRAB
  ('Linhphinn Phuong', NULL, 'Nhờ việc học ở đây mà e đã đỡ dựng hình sai nhiều hơn 💖💖 …', 5, 'Google Maps', true),  -- [TRUNCATED] 5 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2pCMFNtSTFSSFZYV0dsS2RXbDZTRmhaWmt4S1IxRRAB
  ('', NULL, 'Giảng viên nhiệt tình, mình học off lâu r mà dạo này có 1 anh mới vô dạy hay quá, còn gọi bút chì giỏi 💛🌾 …', 5, 'Google Maps', true),  -- [TRUNCATED] 10 tháng trước · ChZDSUhNMG9nS0VJalUxNE9zZ2JxLU9REAE
  ('Zăn Khang', NULL, 'Tuy chỉ mới hc có 2 tháng thui, nhưng mình đã tiến bộ lên rất nhiều, thầy Hoàng lớp mình hc siêu siêu dễ thương và tận tình,  cảm ơn Sine Art nhiều nhee', 5, 'Google Maps', true),  -- 10 tháng trước · ChdDSUhNMG9nS0VPbVU2Y2VFMFlMajdRRRAB
  ('Thu Trang Nguyen', NULL, 'giảng viên siu có tâm, siu tận tuỵ, dạy siu siu dễ hiểu luân ạ; lớp học thoải mái mát mẻ, trung tâm hỗ trợ nhiệt tình, học viên ôn thi hết mình. Môi trường giáo dục tuyệt vời, quá là thích rất là yêu ạ, phải gọi là ưng quá chừng luôn á 💋💋💋 …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChdDSUhNMG9nS0VJQ0FnSURyaVAzRTVBRRAB
  ('Diệp Cẩm Quỳnh', NULL, 'Mik học onl ở đây, giảng viên dễ thương lúm. Tận tâm chăm sóc học viên lắm luôn ad. (´,,•ω•,,)♡', 5, 'Google Maps', true),  -- 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2pNeVJrRk5hV1JqY21SbFdXbHpaVzU2ZW5sM2QyYxAB
  ('', NULL, 'Trung tâm giảng dạy tốt, giảng viên nhiệt tình và thấu hiểu học viên. 10/10 luôn hihi', 5, 'Google Maps', true),  -- 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2xoa05rZEZWVVl0WlVSWk4xRm1TRUZXZGsweVUxRRAB
  ('Tường Nghi', NULL, 'Giảng viên có tâm, nhiệt huyết với thân thiện lắm ạ. Vì học theo giáo trình và có vid lí thuyết nữa nên học hiệu quả lắm chứ không phải chỉ học để thi thôi, cực recommend nha ✨️', 5, 'Google Maps', true),  -- một năm trước · ChZDSUhNMG9nS0VJQ0FnSUNyMjc3VERBEAE
  ('Trung Kiên', NULL, 'Khi mới bắt đầu tìm hiểu về ttm và ôn thi năng khiếu, mình không biết phải chọn lớp nào bởi vì mình không biết nhiều lắm về các lớp vẽ, có thể nói mình đã tìm hiểu duy nhất 1 lớp và đưa ra quyết định học chính là Sine Art. Tuy hơi vội vàng …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChdDSUhNMG9nS0VJQ0FnSUMzNFlyb3h3RRAB
  ('Hải Thuỵ', NULL, 'Giảng viên siu có tâm, mặc dù học onl nhm giảng viên siu tận tình, sửa bài siu kĩ mà còn thân thiện nữa. Lụy trung tâm qá 💗💗. Cảm thấy học ở Sine là lựa chọn chính xáccccccc …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChZDSUhNMG9nS0VJQ0FnSUNydEtTcEVBEAE
  ('Hoài Thương Lê', NULL, 'Em học onl môn bố cục tranh màu.
Môn học có giáo trình bài bản.
Các giảng viên rất tận tâm, nhiệt tình không chỉ trong giờ học mà còn sửa bài …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNyM1pLXzNnRRAB
  ('my nguyen', NULL, 'mình học khóa onl thấy giảng viên chữa bài rất kĩ và có sẵn các video minh họa rất dễ hiểu rất đáng hc nha', 5, 'Google Maps', true),  -- một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNfMnZxVzhRRRAB
  ('Phương Trà Nguyễn', NULL, 'dạy đỉnh cực luôn ấy, giảng viên rất quan tâm học viên, bên trung tâm cũng hỗ trợ nhiệt tình, chỉ ôn thi 6 tháng mà nhận được nhiều từ phía trung tâm lắm <3', 5, 'Google Maps', true),  -- một năm trước · ChZDSUhNMG9nS0VJQ0FnSUNUM291TWJ3EAE
  ('02.Lê Thị Kim Cương', NULL, 'Lớp vễ huông, bạn trong lớp và giảng viên vui vẻ thân thiện. Môi trường học chill. Highly recommend ae học tại đây thì giảng và sửa bài offline rất kỹ. Online thì nên cân nhắc nhma gv cũng nhiệt tình nên cũng ổn. Học hong bao lâu nhma sine art đã dạy mình gấc nhìu thứ tuỵt zời ^q^', 5, 'Google Maps', true),  -- một năm trước · ChZDSUhNMG9nS0VJQ0FnSUNuNHVPMVdREAE
  ('An Nguyễn', NULL, 'Đây là trung tâm đầu tiên mình chọn để theo học và tới giờ vẫn k có ý định đổi nhen✨✨ giảng viên thân thiện, giàu kinh nghiệm, truyền đạt tốt, môi trường học thoải mái, học phí cực rẻ mà đầy đủ tiện nghi❤️‍🔥. Vị trí ngay cạnh bãi đất nhiều …', 5, 'Google Maps', true),  -- [TRUNCATED] 2 năm trước · ChdDSUhNMG9nS0VJQ0FnSURENFpDTi1BRRAB
  ('TrungTin Tran', NULL, 'trung tâm đầu tiên mình học cấp tốc để thi đh, gv có tâm, chương trình giảng dạy rất ổn, trong tg ngắn mình vấn đủ kiến thức để thi, tóm lại rất đáng để chọn đây là nơi để mọi người phát triển kĩ năng  về hội họa', 5, 'Google Maps', true),  -- một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNUZ05qWHlRRRAB
  ('Danh Hoàng Thái', NULL, 'Giảng viên nhiệt tình và hiệu quả ạ', 5, 'Google Maps', true),  -- 3 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT25CaVRXOXhWRzUyZGxka1FsQkVibEI2ZHpBNU5XYxAB
  ('Mai Anh Ngô', NULL, 'Rất oke, giảng viên nhiệt tình trong giờ dạy và cả ngoài giờ, dễ hiểu ạ.', 5, 'Google Maps', true),  -- 7 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2tSQ1lWSklOVXd3TTNBd1dXaHRRMVpGYTI5MGFYYxAB
  ('Thy Trang', NULL, 'Sineart với mình 10đ ko có nhưng, học phí giá rẻ học tẹt ga 1 tháng 48 buổi cũng đc quá đã 😋 gv sửa bài chi tiết siêu có tâm, lộ trình các môn rõ ràng rất chắc phần cơ bản, ngoài ra thì mình còn được dạy những kiến thức rộng hơn ko chỉ là luyện thi vào đh, môi trường thân thiện csvc oki ✨ rcm mn nên học 🙆🙆🙆 …', 5, 'Google Maps', true),  -- [TRUNCATED] Thời gian chỉnh sửa: một năm trước · ChdDSUhNMG9nS0VJQ0FnSUREaVl6eWdRRRAB
  ('', NULL, '+1 nên học Sine, chất lượng thì hong phải bàn cộng thêm mấy ac ở Sine ai cũng siu tâm huyết siu dễ thương 💖 …', 5, 'Google Maps', true),  -- [TRUNCATED] 10 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2xSZlEyMHlaRTg0Tkc1M1RUZHljQzFpU0haelEzYxAB
  ('wan chan', NULL, 'Lúc đầu biết đến Sine là vì xem được vài video hướng dẫn bên nì trên youtube, sau đó mới học thử khoá online, rồi mình chuyển sang học offline luôn.
Huhuuu phải nói là các anh chị  siu có tâm 🥹, sửa bài siu siu chỉnh chu chi tiết …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChZDSUhNMG9nS0VJQ0FnSUNycjhtMEhnEAE
  ('Tú Cẩm', NULL, 'dạ trung tâm đáng iu lắm ạ, học cũng ổn áp cực nch 10 đỉm ạa ୧( ⁼̴̶̤̀ω⁼̴̶̤́ )૭', 5, 'Google Maps', true),  -- 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2xsa1ZWaGtkVlUwV0dWUmFGZDFYeTFqVVZKUmVIYxAB
  ('Hoàng Tài', NULL, 'Anh chị giảng viên dạy siêu tâm huyết và tận tình luôn, hệ thống bài giảng, bài tập đối với mình là dễ hiểu và khá tiện cho mình, mừ điểm nhóo', 5, 'Google Maps', true),  -- một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNIOHNUVWpnRRAB
  ('nguyen Loan', NULL, 'Trung tâm đỉnh lắm ạ huhu 😭❤️ …', 5, 'Google Maps', true),  -- [TRUNCATED] 9 tháng trước · Ci9DQUlRQUNvZENodHljRjlvT2xGdk0xaEpaV05GWWxvNVExWmxWVU5PV0VKSmQyYxAB
  ('Vy Hồ', NULL, '50đ cho sự dễ thương, tận tình chu đáo và hài hước của giảng viên
thêm 50đ cho lộ trình học và bài giảng vô cùng dễ hiểu
cộng lại 100đ cho sự tuyệt vời của lớp học
(1000000đ cho máy lạnh mát rười rượi)', 5, 'Google Maps', true),  -- một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNyNklpVXJ3RRAB
  ('Long Bảo', NULL, '+♾️ điểm
Giảng viên siêu chất lượng vừa xinh gái vừa dạy tốt dễ hiểu
Cơ sở mới siêu xịn siêu đầy đủ tiện nghi …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNMaWRiQWpRRRAB
  ('', NULL, 'giảng viên luôn take care hs, rất tận tâm, nhiệt tình luôn ấy ạ, lộ trình học cũng rõ ràng, mình học tầm 2 tháng trước khi thi thui mà hối hận không biết đến trung tâm sớm hơn, tại học onl mà mình cảm thấy còn hiệu quả hơn chỗ mình từng học off nữa...', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNUMVpya3BRRRAB
  ('Nhu Nguyen', NULL, 'Lớp vẽ thực sự rất tuyệt dời lun!! Tớ chọn học online bên Sine Art do bất tiện đi lại. Với 1 đứa để nước "tới chân mới nhảy" như tớ thì việc theo học Trang trí màu rất trễ (cụ thể là hè năm 11 lên 12) nhưng phần lớn giảng viên đã giúp tớ …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChZDSUhNMG9nS0VJQ0FnSUNMLXE2alZBEAE
  ('Linh Phương Nguyễn', NULL, 'Rất mê Sine Art vì có giáo trình bài bản, giảng viên hỗ trợ nhiệt tình lắm nè, trung tâm cũng rất tâm lý nữa ạ. 100₫ không có nhưng ạ', 5, 'Google Maps', true),  -- một năm trước · ChZDSUhNMG9nS0VJQ0FnSUNyLXJlb2FREAE
  ('Vy Trúc', NULL, 'Lộ trình học rõ ràng, giáo viên giảng bài dễ hiểu, dễ thương và quan tâm giúp đỡ cũng như giải đáp mọi thắc mắc của học viên, nói chung 10 đỉm khum có nhưng <33', 5, 'Google Maps', true),  -- một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNyM2F6QnNBRRAB
  ('Quế Đinh', NULL, 'E hc lớp cấp tốc e thấy rất tuyệt vời:)))), giảng viên dạy rất có tâm vs nghề', 5, 'Google Maps', true),  -- một năm trước · ChZDSUhNMG9nS0VJQ0FnTUR3NE4yOVFBEAE
  ('Ngân Nguyễn', NULL, 'Mấy anh chị giảng viên dễ thương lắm mn oi, sửa bài kĩ, còn có sửa bài ngoài giờ nữa, lộ trình khá bài bản nên mấy b chưa biết gì về vẽ mà muốn học vẫn okela lắm nhe,còn có nhiều bài giúp mình có nền tảng sẵn khi lên đh nữa á chứ k phải chỉ học để thi thôi', 5, 'Google Maps', true),  -- một năm trước · ChdDSUhNMG9nS0VJQ0FnSURILUtUQ21BRRAB
  ('Thành Trương', NULL, 'Sine art rất chất lượng và nhiệt tình nha,mình chỉ học 4 tháng mà giải gần 20 đề luôn vì đc giảng viên hỗ trợ sửa bài ngoài giờ nữa', 5, 'Google Maps', true),  -- một năm trước · ChZDSUhNMG9nS0VJQ0FnSURMX0tHY0RREAE
  ('Thanh Vy', NULL, 'Đội ngũ và các ac giảng viên bên Sine Art siêu nhiệt tình và dễ thương 10 điểm k có nhưng. Các ac hướng dẫn em rất chi tiết từng bài vẽ dù hc onl nma em cảm thấy hiệu quả vô cùng. Sửa bài sieuu kỹ và rất dễ hiểu luon í!!! Chúc trung tâm Sine Art sẽ ngày càng phát triển và thành công hơn ạ🫶🩷🩷🩷 …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNMM0tiSzh3RRAB
  ('Hớn Phong Vưu', NULL, 'Lớp học có liệu trình học rõ ràng giảng viên dth lémmm học cũng dễ hiểu nữa các a chị ad cũng tận tâm lắmmmm rcm nên học nhe 10đ khum có nhưng 😋😋💥💖 …', 5, 'Google Maps', true),  -- [TRUNCATED] một năm trước · ChZDSUhNMG9nS0VJQ0FnSUNycmU2WFV3EAE
  ('Hoa Trần', NULL, 'giảng viên rất nhiệt tình và đáng yêu, mấy ac qli trung tâm sẵn sàng hỗ trợ mọi lúc, lộ trình học định hướng rõ ràng, 100/10, nếu các bạn đang phân vân thì chốt ngay nhe, h mình là tân sinh viên đh rồi neee 😘 …', 5, 'Google Maps', true);  -- [TRUNCATED] một năm trước · ChdDSUhNMG9nS0VJQ0FnSUNMN3NtcXlnRRAB
