-- Giá trị tài sản (admin) — bảng tc_tai_san_rong · khấu hao tính phía app (theo Framer VH_Gia tri tai san).
CREATE TABLE IF NOT EXISTS public.tc_tai_san_rong (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten_tai_san text NOT NULL,
  loai_tai_san text,
  ngay_mua date,
  gia_tri_moi_mua numeric NOT NULL DEFAULT 0,
  thoi_gian_khau_hao integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.tc_tai_san_rong ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tc_tai_san_rong TO service_role;
GRANT ALL ON TABLE public.tc_tai_san_rong TO postgres;

COMMENT ON TABLE public.tc_tai_san_rong IS
  'Tài sản & nguyên giá; khấu hao lũy kế theo tháng tính trên client (gia_tri_moi_mua, thoi_gian_khau_hao tháng, ngay_mua).';

NOTIFY pgrst, 'reload schema';
